// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsTVhvBP0ye73PU4PWV6MvfBrIMkb80nQ',
    appId: '1:340772902528:web:c8ef6d22e310af8e8e7865',
    messagingSenderId: '340772902528',
    projectId: 'doctor-hunt-app-2026',
    authDomain: 'doctor-hunt-app-2026.firebaseapp.com',
    storageBucket: 'doctor-hunt-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-xLXIU_ktsN1B2JzkY4cdCHreFHb_X70',
    appId: '1:340772902528:ios:70d8b33c962db6ad8e7865',
    messagingSenderId: '340772902528',
    projectId: 'doctor-hunt-app-2026',
    storageBucket: 'doctor-hunt-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-xLXIU_ktsN1B2JzkY4cdCHreFHb_X70',
    appId: '1:340772902528:ios:70d8b33c962db6ad8e7865',
    messagingSenderId: '340772902528',
    projectId: 'doctor-hunt-app-2026',
    storageBucket: 'doctor-hunt-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsTVhvBP0ye73PU4PWV6MvfBrIMkb80nQ',
    appId: '1:340772902528:web:8a3964993372d5d68e7865',
    messagingSenderId: '340772902528',
    projectId: 'doctor-hunt-app-2026',
    authDomain: 'doctor-hunt-app-2026.firebaseapp.com',
    storageBucket: 'doctor-hunt-app-2026.firebasestorage.app',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASNZMkXgVgiRwHpU1dqketyge9n2lLLTM',
    appId: '1:340772902528:android:2cb41168d606761e8e7865',
    messagingSenderId: '340772902528',
    projectId: 'doctor-hunt-app-2026',
    storageBucket: 'doctor-hunt-app-2026.firebasestorage.app',
  );
}
